{% set name = "simphyni" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  # script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python=3.11
    - pip
    - setuptools
    - wheel
  run:
    # conda dependencies
    - python>=3.11,<3.12
    - ete3>=3.1.3
    - joblib>=1.4.2
    - matplotlib>=3.10.1
    - numpy>=2.2.3
    - pandas>=2.2.3
    - plotly>=6.0.0
    - scikit-learn>=1.6.1
    - seaborn>=0.13.0,<0.14
    - setuptools>=75.8.0
    - statsmodels>=0.14.4
    - wheel>=0.45.1
    - snakemake>=9.10.0
    - pip
    # pip-only dependencies (from your environment.yml)
    - pip:
        - annotated-types>=0.7.0
        - biopython>=1.85
        - certifi>=2025.1.31
        - charset-normalizer>=3.4.1
        - idna>=3.10
        - itolapi>=4.1.5
        - jinja2>=3.1.6
        - markupsafe>=3.0.2
        - pastml>=1.9.50
        - pydantic>=2.10.6
        - pydantic-core>=2.27.2
        - requests>=2.32.3
        - scipy>=1.14.0
        - urllib3>=2.4.0


test:
  commands:
    - simphyni --help
    - simphyni run --help
    - python -c "import simphyni; print(simphyni.__version__)"
    - snakemake version

about:
  home: "https://github.com/jpeyemi/simphyni"
  license: "MIT"
  summary: "SimPhyni: a tool for phylogenetic trait simulation and inference."

extra:
  recipe-maintainers:
    - jpeyemi
